[build] stop committing models to source control (#55)
Instead of committing large binary files & dealing with merge conflicts:

* `cd ml.net/InclusiveCodeReviews.Convert && dotnet run` will place both model files in `bin` in the root of the repo
* We archive these files as artifacts
* Update various docs to mention changes

One thing that is weird, is some test started failing, such as:

      1) I don't like this.:
      AssertionError: expected 0.6322438716888428 to be above 0.7

I made changes to workaround this. It must be the model creation is *not* deterministic.

~~ Other changes ~~

* Duplicate row found in `classified.csv`
* Replace punctation at end of test text. TODO, do this across the board.
* Additional versions of "I do not like this"
* Rename workflow / jobs