Load an example .csv with real data
This bombs out with:

    Error: Invalid row in csv file. Should have 5 elements in a row, but got

I think the line breaks are causing issues.